name: team_up_desktop
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.4
  async_builder: ^1.3.1
  json_serializable: ^6.5.3
  rxdart: ^0.27.5
  uuid: ^3.0.7
  json_annotation: ^4.8.0
  get_it: ^7.2.0
  flutter_svg: ^2.0.7

  # Modules
  library_pkg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: baloo
      fonts:
        - asset: assets/fonts/baloo_regular.ttf
